[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
agent_registry = "5ND2gro8VfRE9xASu6zB1FPfKeH3Sf86hgkCkRmjFFBW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-temp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
